#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
# (except homebrew, which has probably already install)
find . -name install.sh -not -path './homebrew/install.sh' | while read installer ; do echo "›" ${installer} && sh -c "${installer}" ; done
